import Head from "next/head";
import React from "react";
import style from "./Layout.module.scss";
import Footer from "../Footer/Footer";
import Header from "../Header/Header";

const Layout: React.FC = ({ children }) => {
  return (
    <>
      <div className={style.container}>
        {/* <Head>
          <title>kitamago-log</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          ></link>
          <link
            href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@500&display=swap"
            rel="stylesheet"
          ></link>
        </Head> */}
        <Header />
        <main className={style.main}>
          <div>{children}</div>
        </main>
        <Footer />
      </div>
    </>
  );
};

export default Layout;
