import Head from "next/head";
import React from "react";
import styles from "../../../styles/Home.module.css";
import Footer from "../Footer/Footer";
import Header from "../Header/Header";

const Layout: React.FC = ({ children }) => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>kitamago-log</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className={styles.main}>
          <div>{children}</div>
        </main>
        <Footer />
      </div>
    </>
  );
};

export default Layout;
